### PR TITLE
Snap not building - fixed issue

### PR DESCRIPTION
**Pull request by kz6fittycent**
Per our discussion on https://forum.snapcraft.io/t/jenkins-snaps-not-building/37368/3

### CODE REVIEW

**Comment by kz6fittycent** [comment]
stand by - I see my error...

**Comment by kz6fittycent** [comment]
That's more like it!

**Comment by kz6fittycent** [comment]
Let me know if there's anything else needed. It's passing builds from my end and I have the locally built snap running in my home network.

**Comment by kz6fittycent** [comment]
nudge...

**Comment by kz6fittycent** [comment]
Not sure why, but the test builds are passing in my repo. I just merged a core22 based version into my master branch, and it's passing. AFAICT, we have the same GH actions.

**Comment by kz6fittycent** [comment]
@merlijn-sebrechts - if you (or another party) don't mind taking another look at this PR, I think it's ready. I say that with some reservation given the experiences I've had with the ~50/50 build failure/success rate. The latest commit is working and I've even upgraded to `core22`. I apologize for the noise from this PR, but it was fairly frustrating to see the difference in outcomes from our two repos.

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

I'm assuming the weird issues were because we're running [snapcraft review-tools](https://snapcraft.io/review-tools) after the build, and you might not be doing that. Snapcraft review-tools is what the store runs before publishing your snap, so all snaps must pass this automated review.

**Pull request merged**
